// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt4sj_EFJNzIoAyG5QS5yI6BAcr9wnsp0',
    appId: '1:143286365004:web:ade441aa407f8206d53de9',
    messagingSenderId: '143286365004',
    projectId: 'projet-flutter-35bae',
    authDomain: 'projet-flutter-35bae.firebaseapp.com',
    storageBucket: 'projet-flutter-35bae.appspot.com',
    measurementId: 'G-WHGXE62Y3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3Q7S4LcAyCUIRsZA7cvLR8QCwonADU0',
    appId: '1:143286365004:android:63d242a1f4d8e057d53de9',
    messagingSenderId: '143286365004',
    projectId: 'projet-flutter-35bae',
    storageBucket: 'projet-flutter-35bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkit5188JiY1oqYgWK6zAN5CayiZm3_pY',
    appId: '1:143286365004:ios:0a91fa4d5794cd78d53de9',
    messagingSenderId: '143286365004',
    projectId: 'projet-flutter-35bae',
    storageBucket: 'projet-flutter-35bae.appspot.com',
    androidClientId: '143286365004-tu2g6qjjhiikoi127ptk2ialns8lvvh3.apps.googleusercontent.com',
    iosClientId: '143286365004-tu82jnlcb5dsqa6pp4k67g7bco4f76fa.apps.googleusercontent.com',
    iosBundleId: 'flutter.projet.projetFlutter',
  );
}
